language: node_js
node_js:
- 4.5.0
before_script:
- chmod +x ./cibuild.sh
- ssh-keyscan -H -t rsa,dsa $hostname >> ~/.ssh/known_hosts
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - CXX=g++-4.8
sudo: false
addons:
  ssh_known_hosts: "$hostname"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_d033e7b71ae3_key -iv $encrypted_d033e7b71ae3_iv -in $TRAVIS_BUILD_DIR/dash.org-test-web.pem.enc -out $TRAVIS_BUILD_DIR/dash.org-test-web.pem -d
- rvm install 2.3.1
before_deploy:
- chmod 600 $TRAVIS_BUILD_DIR/dash.org-test-web.pem
- eval `ssh-agent -s`
- ssh-add $TRAVIS_BUILD_DIR/dash.org-test-web.pem
- cp $TRAVIS_BUILD_DIR/dash.org-test-web.pem ~/.ssh/id_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r -c -v --delete-after --exclude-from 'ciexclude.txt' $TRAVIS_BUILD_DIR/_site/ user@$hostname:$production_path
  on:
    branch: master
